title: HBRL Research Group
description: Merge our knowledge beyond brain limits

remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

header_pages:
  - research.md
  - leader.md
  - team.md
  - publications.md
  - presentations.md
  - facility.md
  - resources.md
