title: HBRL Research Group
description: Atomic Layer Deposition & Materials Chemistry
url: "https://hbrleelab.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

# 기본 레이아웃
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      sidebar:
        - title: ""
          text: "{% include sidebar-news.html %}"
                 
minimal_mistakes_skin: "default"
