title: HBRL Research Group
description: Atomic Layer Deposition & Materials Chemistry

remote_theme: pages-themes/modernist@v0.2.0

plugins:
  - jekyll-remote-theme

header_pages:
  - research.md
  - leader.md
  - team.md
  - publications.md
  - presentations.md
  - facility.md
  - resources.md
