theme: jekyll-theme-minimal

title: HBRL Research Group

navigation:
  - title: Home
    url: /
  - title: People
    url: /people
  - title: Research
    url: /research
  - title: Publications
    url: /publications
  - title: Facility
    url: /facility
