title: HBRL Research Group
description: Atomic Layer Deposition & Materials Chemistry
url: "https://hbrleelab.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
